typography_spectrum: 0.19071
color:
  brandColors:
    - '#632c50'
    - '#000000'
    - '#400040'
    - '#660033'
    - '#800000'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: SalesBrief
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: figmints thoughtstream
purpose: []
