name: Jam
favicon: null
layout_spectrum: 0.04046042379923165
typography_spectrum: 0.1668471226003021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6712806983850896
  lightness: 0.3442550248000771
  saturation: 0.7321061524562538
  rhythmicContrast: 0.785604166565463
purpose: []
